### ISSUE TITLE
Deleting mod feature handles exception incorrectly

### ISSUE THREAD

**Issue by lennoxtr** [AY2223S2-CS2103-F10-2/tp#196]
**Description**
When executing delete mod command with incorrect format input, no Invalid Command Format error is shown to the user on Le Tracker, instead a an error is thrown on the console

**Steps for reproducing**
`delete /mod CS2040S`

**Expected result**
Incorrect format message shown on Le Tracker

**Actual result**
java.lang.reflect.InvocationTargetException thrown on console

**Other details**

**Error output**
![image](https://user-images.githubusercontent.com/98014932/228207413-f75ae69e-46b7-4cef-ba65-61a101a84255.png)

![image](https://user-images.githubusercontent.com/98014932/228208690-9dae3ea9-e9b4-4d56-a325-df126c941b26.png)

``` Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1784)
	... 47 more
Caused by: java.lang.IllegalArgumentException: Lecture names should only contain alphanumeric characters and spaces, and it should not be blank
	at seedu.address.commons.util.AppUtil.checkArgument(AppUtil.java:39)
	at seedu.address.model.Name.<init>(Name.java:37)
	at seedu.address.model.Name.<init>(Name.java:26)
	at seedu.address.model.lecture.LectureName.<init>(LectureName.java:20)
Caused by: java.lang.IllegalArgumentException: Lecture names should only contain alphanumeric characters and spaces, and it should not be blank

	at seedu.address.logic.parser.DeleteCommandParser.parse(DeleteCommandParser.java:45)
	at seedu.address.logic.parser.TrackerParser.parseCommand(TrackerParser.java:73)
	at seedu.address.logic.LogicManager.execute(LogicManager.java:58)
	at seedu.address.ui.MainWindow.executeCommand(MainWindow.java:207)
	at seedu.address.ui.CommandBox.handleCommandEntered(CommandBox.java:53)
	... 59 more
```

**Comment by hingen** [comment]
Would be useful to paste the full error output (if you have it) as a code block so that one can see the stack trace and use `ctrl+f` to find relevant information
